build:
  pre_ci:
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/puppet:jessie .
  pre_ci_boot:
    image_name: mygento/puppet
    image_tag: jessie
    pull: false
  ci:
    - puppet -V
  push:
    - docker tag -f mygento/puppet:jessie mygento/puppet:latest
    - docker push mygento/puppet:jessie
    - docker push mygento/puppet:latest

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
