build:
  pre_ci:
    - docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag=mygento/puppet:latest .
  pre_ci_boot:
    image_name: mygento/puppet
    image_tag: latest
    pull: false
  ci:
    - puppet -V
  push:
    - docker push mygento/puppet:latest

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
